### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by vlisivka** [zrzka/anes-rs#22]
I want to use anes for Arduino serial I/O, but cannot, because it requires std. Can we make a no_std version of anes, or it's better to fork it?

**Comment by zrzka** [comment]
I don't have enough time for this project these days. Two options:

* you can fork it,
* I can transfer the repo to your account along with the crates.io permissions to be able to release new versions, ...

**Comment by vlisivka** [comment]
uwrite doesn't work in macros, because it implemented as procedural macro, so I cannot use anes at Arduino anyway. :-(

I have no free time to become a maintainer either.
